# Generated by Django 5.1.2 on 2024-10-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='type',
            new_name='card_type',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='dob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
